### ISSUE TITLE
proper utf-8 encoding

### ISSUE THREAD

**Issue by SoupMeNot** [folz/cleverbot.py#27] opened 2016-05-20 23:30 UTC
There are several issues with encoding utf-8 characters (at least with the german ones that i'm trying).

First, the example has an issue with:
`print('>> Cleverbot: {}'.format(answer))`

A common error is:
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)

I patched this by dropping the format-function:
`print('>> Cleverbot:'+answer)`

So I played around a little bit, but when cleverbot answers me some utf-8 characters, this happens:
`
 >>Cleverbot: HÃ¤Ã¤Ã¤Ã¤???
 >>You: test
Traceback (most recent call last):
  File "cbtest.py", line 21, in <module>
    main()
  File "cbtest.py", line 15, in main
    answer = cleverbot_client.ask(question)
  File "/home/wernerp/dev/python/cleverbot.py", line 95, in ask
    resp = self._send()
  File "/home/wernerp/dev/python/cleverbot.py", line 131, in _send
    enc_data = urlencode(self.data)
  File "/usr/lib/python2.7/urllib.py", line 1349, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1-8: ordinal not in range(128)
`

When I try to pre-format the string to be convertible for urlencode, always the cleverbot-site kicks in and DENIES the access. I assume, that the token, produced from an escaped unicode-string isn't the same as calculated on the website....

any suggestions? Sorry for my english, oh, and i'm fairly a python-beginner, i just need it for this project....

**Comment by folz** [comment] 2016-05-21 02:53
This is probably the same root cause as #21. I haven't had the free time to delve into the issue, sorry. I'm going to close this issue in favor of keeping discussion over there - please subscribe to #21 so you can get updated if/when I figure out how to solve it.

If you could paste some of the German questions you're asking in the other thread (so I can use them in my own testing) I'd really appreciate it!

**Closed by folz** 2016-05-21 02:53 UTC
